Loadup failure ldeinit (#286)
* a litte better info and checking

* fix typo

Co-authored-by: Larry Masinter <LMM@acm.org>

diff --git a/run-medley b/run-medley
--- a/run-medley
+++ b/run-medley
@@ -172,12 +172,16 @@ export PATH="$MAIKODIR"/`osversion`.`machinetype`:"$oldpath"
 
 cd "$OLDPWD"
 
-echo "sysout is $LDESRCESYSOUT"
-echo "running `which $prog` $geometry $screensize $mem"
-echo "start $LDEINIT"
+if ! command -v "$prog" > /dev/null 2>&1; then
+    echo "$prog" not found
+    exit 1
+fi
+
+echo "running: $prog $geometry $screensize $mem $passthrough_args $LDESRCESYSOUT"
+echo "greet: $LDEINIT"
 
 export INMEDLEY=1
 
-$prog $geometry $screensize $mem -t "Medley Interlisp" $passthrough_args "$LDESRCESYSOUT"
+"$prog" $geometry $screensize $mem -t "Medley Interlisp" $passthrough_args "$LDESRCESYSOUT"
 
 
