Update run-medley

diff --git a/run-medley b/run-medley
--- a/run-medley
+++ b/run-medley
@@ -32,8 +32,19 @@ setenv OSVERSION `uname -r`
 
 # Directory variables are accessible from Lisp via UNIX-GETENV
 
-if (! $?MEDLEYDIR ) setenv MEDLEYDIR "$HOME/medley"
-if (! $?MAIKODIR )  setenv MAIKODIR $MEDLEYDIR/../maiko
+if (! $?MEDLEYDIR ) setenv MEDLEYDIR `pwd`
+if (! -d $MEDLEYDIR/loadups ) then
+   echo MEDLEYDIR not found: "$MEDLEYDIR"
+   exit 1
+endif
+
+if (! $?MAIKODIR ) then
+   setenv MAIKODIR $MEDLEYDIR/../maiko
+   if (! -d "$MAIKODIR"/bin ) then
+    echo "MAIKODIR not found: $MAIKODIR"
+    exit 1
+   endif
+endif
 
 setenv LDEINIT "$MEDLEYDIR/initfiles/local-init"
 
@@ -124,7 +135,7 @@ if ($#argv != 0) then
 				set name=`expr substr $1 2 999`
 				setenv LDESRCESYSOUT "$MEDLEYDIR/loadups/${name}.sysout"
 			else # not an option so must be a sysout name
-				setenv LDESRCESYSOUT $1
+		0		setenv LDESRCESYSOUT $1
 			endif
 		breaksw
 	 endsw
@@ -183,9 +194,9 @@ echo "using emulator version $version"
    case "3.5":
    case "3.501":
     
-setenv PATH .:$PATH
-pushd $MAIKODIR/bin
-setenv PATH $MAIKODIR/`osversion`.`machinetype`:$PATH
+setenv PATH .:"$PATH"
+pushd "$MAIKODIR"/bin
+setenv PATH $MAIKODIR/`osversion`.`machinetype`:"$PATH"
 popd
 
 #	if ${?DISPLAY} then	 # we are running under X
