Try again to fix handling of bad maiko tag

diff --git a/.github/workflows/buildLoadup.yml b/.github/workflows/buildLoadup.yml
--- a/.github/workflows/buildLoadup.yml
+++ b/.github/workflows/buildLoadup.yml
@@ -146,8 +146,10 @@ jobs:
             tag=$(gh release list --repo ${{ github.repository_owner }}/maiko | grep Latest | head -n 1 | awk '{ print $3 }')
           else
             tag=${{ inputs.maiko_release }}
-            gh release view ${tag} --repo ${{ github.repository_owner }}/maiko ; err=$? || true
-            if [ ${err} -ne 0 ]; then echo "!!!!!!! Error:  Cannot find Maiko release ${tag}. Exiting."; exit 1; fi
+            set +e
+            gh release view ${tag} --repo ${{ github.repository_owner }}/maiko
+            if [ $? -ne 0 ]; then echo "!!!!!!! Error:  Cannot find Maiko release ${tag}. Exiting."; exit 1; fi
+            set -e
           fi
           echo "maiko_tag=${tag}" >> ${GITHUB_OUTPUT}
         env:
