i buildLoadp.yml enabeer too specify tag for maiko-release to be used.

diff --git a/.github/workflows/buildLoadup.yml b/.github/workflows/buildLoadup.yml
--- a/.github/workflows/buildLoadup.yml
+++ b/.github/workflows/buildLoadup.yml
@@ -20,18 +20,18 @@ name: Build/Push Medley Release
 on:
   workflow_dispatch:
     inputs:
+      maiko_release:
+        description: "What maiko release to use"
+        type: string
+        default: 'Latest'
       draft:
         description: "Mark this as a draft release"
-        type: choice
-        options:
-        - 'false'
-        - 'true'
+        type: boolean
+        default: false
       force:
         description: "Force build even if build already successfully completed for this commit"
-        type: choice
-        options:
-        - 'false'
-        - 'true'
+        type: boolean
+        default: false
 
   workflow_call:
     outputs:
@@ -39,16 +39,21 @@ on:
         description: "'True' if medley build completed successully"
         value: ${{ jobs.complete.outputs.build_successful }}
     inputs:
+      maiko_release:
+        description: "What maiko release to use"
+        required: false
+        type: string
+        default: 'Latest'
       draft:
         description: "Mark this as a draft release"
         required: false
-        type: string
-        default: 'false'
+        type: boolean
+        default: false
       force:
         description: "Force build even if build already successfully completed for this commit"
         required: false
-        type: string
-        default: 'false'
+        type: boolean
+        default: false
     secrets:
       OIO_SSH_KEY:
         required: true
@@ -110,7 +115,7 @@ jobs:
     needs: [sentry]
     if: |
       needs.sentry.outputs.release_not_built == 'true'
-      || inputs.force == 'true'
+      || inputs.force == true
 
     steps:
       # Checkout the actions for this repo owner
@@ -130,24 +135,19 @@ jobs:
         id: tag
         uses: ./../actions/release-tag-action
 
-      # Get Maiko release information, retrieves the name of the latest (draft)
+      # Get Maiko release information, use maiko release tag from input or Latest
       # release.  Used to download the correct Maiko release
-      # Find latest release (draft or normal)
       - name: Get maiko release information
         id: maiko
         run: |
           tag=""
-          if [ "${{ inputs.draft }}" = "true" ];
-          then
-            gh release list --repo ${{ github.repository_owner }}/maiko | grep Draft >/tmp/releases-$$
-            if [ $? -eq 0 ];
-            then
-              tag=$(head -n 1 /tmp/releases-$$ | awk '{ print $3 }')
-            fi
-          fi
-          if [ -z "${tag}" ];
+          if [ "${{ inputs.maiko_release }}" = "Latest" ];
           then
             tag=$(gh release list --repo ${{ github.repository_owner }}/maiko | grep Latest | head -n 1 | awk '{ print $3 }')
+          else
+            tag=${{ inputs.maiko_release }}
+            gh release view ${tag} --repo ${{ github.repository_owner }}/maiko
+            if [ $? -ne 0 ]; then echo "!!!!!!! Error:  Cannot find Maiko release ${tag}. Exiting."; exit 1; fi
           fi
           echo "maiko_tag=${tag}" >> ${GITHUB_OUTPUT}
         env:
@@ -262,7 +262,7 @@ jobs:
     needs: [sentry, loadup]
     if: |
       needs.sentry.outputs.release_not_built == 'true'
-      || inputs.force == 'true'
+      || inputs.force == true
 
     steps:
 
@@ -338,7 +338,7 @@ jobs:
     needs: [sentry, loadup]
     if: |
       needs.sentry.outputs.release_not_built == 'true'
-      || inputs.force == 'true'
+      || inputs.force == true
 #    if: false
 
     defaults:
@@ -409,7 +409,7 @@ jobs:
     needs: [sentry, loadup, linux_installer]
     if: |
       needs.sentry.outputs.release_not_built == 'true'
-      || inputs.force == 'true'
+      || inputs.force == true
 
     outputs:
       cygwin_installer: ${{ steps.compile_iss.outputs.CYGWIN_INSTALLER }}
@@ -512,7 +512,7 @@ jobs:
     needs: [sentry, loadup, linux_installer, macos_installer, cygwin_installer]
     if: |
       needs.sentry.outputs.release_not_built == 'true'
-      || inputs.force == 'true'
+      || inputs.force == true
 
     steps:
 
